datasources:
  postgres:
    url: "jdbc:postgresql://host:5432/kestra"
    driver-class-name: org.postgresql.Driver
    username: "seu_user"
    password: "sua_senha"

kestra:
  server:
    basic-auth:
      enabled: true
      username: "admin@example.com"
      password: "mudarAgora"
  repository:
    type: postgres
  storage:
    type: local
    local:
      base-path: "/app/storage"
  queue:
    type: postgres
  tasks:
    tmp-dir:
      path: "/tmp/kestra-wd/tmp"
  url: "https://kestratemplaterailway-production.up.railway.app/"