datasources:
  postgres:
    url: "jdbc:postgresql://<POSTGRES_HOST>:<POSTGRES_PORT>/<POSTGRES_DB>"
    driver-class-name: org.postgresql.Driver
    username: "<POSTGRES_USER>"
    password: "<POSTGRES_PASSWORD>"

kestra:
  server:
    basic-auth:
      enabled: true
      username: "<USERNAME>"
      password: "<PASSWORD>"
  repository:
    type: postgres
  storage:
    type: local
    local:
      base-path: "/app/storage"
  queue:
    type: postgres
  tasks:
    tmp-dir:
      path: "/tmp/kestra-wd/tmp"
  url: "https://<RAILWAY_PUBLIC_DOMAIN>/"   # ex: https://your-service.up.railway.app/
